<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title> My First Webpage</title>
</head>
<body>
  <table border="1">
    <tr>
    <td>columu 1</td>
    <td>columu 2</td>
    <td>columu 3</td>
    </tr>
    <tr>
        <td rowspan="2">Row 1 Cell 1</td>
        <td>Row 1 Cell 2 </td>
        <td>Row 1 Cell 3 </td>
       </tr>
       <tr>
        <td>Row 2 Cell 2</td>
        <td>Row 2 Cell 3</td>
  <table border="1">
    <tr>
      <th colspan=
      <th>Value</th>
      <th>Low</th>
      <th>High</th>
    </tr>
    <tr>
        <td>HP</td>
        <td>78</td>
        <td>266</td>
        <td>360</td>
      </tr>
    </table>
</body>
</html>
